# Generated by Django 3.1.7 on 2021-03-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
